export const concepts = [
  {
    id: 'restaurant',
    name: 'Ember & Vine',
    industry: 'Restaurant',
    line: 'A reservation-first neighborhood dining experience.',
    image: 'assets/concepts/ember-vine.jpg',
    interest: 'Restaurant / hospitality',
    request: 'I’m interested in a restaurant website inspired by the Ember & Vine concept.'
  },
  {
    id: 'events',
    name: 'NightShift Audio',
    industry: 'DJ & events',
    line: 'A high-energy booking site built around packages and availability.',
    image: 'assets/concepts/nightshift-audio.jpg',
    interest: 'DJ / events',
    request: 'I’m interested in a DJ or events website inspired by the NightShift Audio concept.'
  },
  {
    id: 'retail',
    name: 'Common Thread Supply',
    industry: 'Retail',
    line: 'An editorial storefront that makes a small collection feel substantial.',
    image: 'assets/concepts/common-thread-supply.jpg',
    interest: 'Retail / ecommerce',
    request: 'I’m interested in a retail website inspired by the Common Thread Supply concept.'
  },
  {
    id: 'goodwork',
    name: 'Goodwork Home Co.',
    industry: 'Home services',
    line: 'A service-area, estimate, scheduling, and dispatch system for the whole home.',
    image: 'assets/concepts/goodwork-home-v1.png',
    interest: 'Home services / field service',
    request: 'I’m interested in a home-services website and dispatch system inspired by the Goodwork Home Co. concept.'
  },
  {
    id: 'morrow',
    name: 'Morrow Dental Studio',
    industry: 'Dental care',
    line: 'A calm care-planning, appointment, insurance, and patient-portal experience.',
    image: 'assets/concepts/morrow-dental-v1.png',
    interest: 'Healthcare / dental practice',
    request: 'I’m interested in a healthcare or professional-services website inspired by the Morrow Dental Studio concept.'
  },
  {
    id: 'relay',
    name: 'Relay North Logistics',
    industry: 'Logistics / B2B',
    line: 'A freight quote, tracking, dashboard, and document system built for operations.',
    image: 'assets/concepts/relay-north-v1.png',
    interest: 'Logistics / B2B operations',
    request: 'I’m interested in a B2B operations website and portal inspired by the Relay North Logistics concept.'
  }
];

const conceptCard = (concept, asset) => `<button class="concept-card concept-card-${concept.id}" type="button" data-open-concept="${concept.id}">
  <span class="concept-card-image"><img src="${asset(concept.image)}" alt="" width="960" height="640" loading="lazy" decoding="async"></span>
  <span class="concept-card-copy"><small>${concept.industry}</small><strong>${concept.name}</strong><span>${concept.line}</span><b>Open interactive concept</b></span>
</button>`;

export function renderConceptLab(asset) {
  const conceptConfig = JSON.stringify(concepts.map(({ id, name, interest, request }) => ({ id, name, interest, request }))).replace(/</g, '\\u003c');
  return `<section id="concepts" class="terminal-section terminal-view concept-lab" aria-labelledby="concepts-title">
    <div class="concept-catalog" id="concept-catalog">
      <div class="section-command" data-boot><span>C:\\JX_LABS&gt;</span><span>run concept_lab.exe</span></div>
      <header class="section-head" data-boot><div><p>CONCEPT LAB</p><h2 id="concepts-title" tabindex="-1">See what your business could become.</h2></div><p>Six fictional brands, built to show how the same web skills can solve very different business problems.</p></header>
      <p class="concept-disclaimer" data-boot>CONCEPT PROJECTS // These are original demonstrations, not client businesses.</p>
      <div class="concept-grid">${concepts.map(concept => conceptCard(concept, asset)).join('')}</div>
    </div>

    <div class="concept-viewer" id="concept-viewer" hidden>
      <div class="concept-toolbar">
        <button type="button" class="concept-tool concept-back" id="concept-back">← Concept lab</button>
        <strong id="concept-viewer-title" tabindex="-1">Concept preview</strong>
        <div class="concept-devices" role="group" aria-label="Preview size">
          <button type="button" class="concept-tool active" data-concept-device="desktop" aria-pressed="true">Desktop</button>
          <button type="button" class="concept-tool" data-concept-device="phone" aria-pressed="false">Phone</button>
        </div>
        <button type="button" class="concept-tool concept-restart" id="concept-restart">Restart</button>
        <button type="button" class="concept-tool concept-request" id="concept-request">Build something like this</button>
      </div>
      <div class="concept-stage">
        <div class="concept-frame" id="concept-frame">
          ${renderRestaurant(asset)}
          ${renderEvents(asset)}
          ${renderRetail(asset)}
          ${renderGoodwork(asset)}
          ${renderMorrow(asset)}
          ${renderRelay(asset)}
        </div>
      </div>
      <p class="concept-toast" id="concept-toast" role="status" aria-live="polite" hidden></p>
    </div>
    <script type="application/json" id="concept-config">${conceptConfig}</script>
  </section>`;
}

function renderRestaurant(asset) {
  const menu = [
    ['snacks', 'Hearth bread', 'Cultured butter, smoked salt', '$8', 'V'],
    ['snacks', 'Crispy squash blossoms', 'Goat cheese, sungold tomato', '$14', 'V'],
    ['snacks', 'Coal-kissed oysters', 'Charred jalapeño mignonette', '$18', 'GF'],
    ['fire', 'Ember-roasted carrots', 'Smoked labneh, pistachio, citrus', '$15', 'V GF'],
    ['fire', 'Half chicken', 'Charred lemon, warm herbs, pan jus', '$29', 'GF'],
    ['fire', 'Gulf redfish', 'Brown butter, caper, market greens', '$34', 'GF'],
    ['fire', '44 Farms bavette', 'Black garlic, embered onion, jus', '$39', 'GF'],
    ['garden', 'Little gem', 'Green goddess, radish, rye crumb', '$13', 'V'],
    ['garden', 'Beets from the coals', 'Blackberry, pecan, sheep’s milk', '$14', 'V GF'],
    ['garden', 'Woodland mushrooms', 'Soft polenta, sherry, parmesan', '$16', 'V GF'],
    ['sweet', 'Burnt honey panna cotta', 'Pear, rosemary sugar', '$11', 'GF'],
    ['sweet', 'Dark chocolate torte', 'Olive oil, sea salt, cocoa nib', '$12', 'V'],
    ['drinks', 'Vine spritz', 'Pear, rosemary, sparkling wine', '$13', ''],
    ['drinks', 'Copper old fashioned', 'Rye, burnt orange, walnut', '$16', ''],
    ['drinks', 'Zero-proof garden', 'Cucumber, mint, tonic', '$10', 'NA']
  ];
  return `<article class="concept-demo restaurant-demo" data-concept-demo="restaurant" hidden>
    <header class="restaurant-nav">
      <button type="button" class="restaurant-wordmark" data-restaurant-route="home" aria-label="Ember and Vine home">Ember <i>&amp;</i> Vine</button>
      <nav aria-label="Ember and Vine pages"><button type="button" data-restaurant-route="menu">Menu</button><button type="button" data-restaurant-route="story">Our table</button><button type="button" class="restaurant-reserve" data-restaurant-route="reserve">Find a table</button></nav>
    </header>

    <main class="restaurant-pages">
      <section class="restaurant-page restaurant-home" data-restaurant-page="home">
        <div class="restaurant-hero">
          <div class="restaurant-hero-copy"><p>Seasonal cooking in Oak Cliff</p><h2>Dinner should feel like a place you found.</h2><span>Fire-led plates, a thoughtful wine list, and a room built for staying awhile.</span><div><button type="button" class="restaurant-primary" data-restaurant-route="reserve">Reserve a table</button><button type="button" data-restaurant-route="menu">Explore tonight’s menu</button></div></div>
          <figure><img src="${asset('assets/concepts/ember-vine-interior-v2.jpg')}" alt="A warmly lit dining room with olive banquettes and an open hearth" width="1586" height="992"><figcaption>DINNER / TUE–SUN / 5–11</figcaption></figure>
        </div>
        <div class="restaurant-marquee" aria-label="Restaurant highlights"><div><span>OPEN HEARTH</span><i>◆</i><span>TEXAS GROWN</span><i>◆</i><span>WINE FOR THE TABLE</span><i>◆</i><span>BISHOP ARTS</span><i>◆</i><span>OPEN HEARTH</span><i>◆</i><span>TEXAS GROWN</span><i>◆</i></div></div>
        <section class="restaurant-signatures">
          <header><p>Tonight at Ember</p><h3>Start with the fire.</h3><button type="button" data-restaurant-route="menu">View full menu <span>↗</span></button></header>
          <figure class="restaurant-dish"><img src="${asset('assets/concepts/ember-vine-dish-v2.jpg')}" alt="Ember-roasted carrots over smoked labneh" width="1448" height="1086"><figcaption><span>01 / From the coals</span><strong>Ember-roasted carrots</strong><small>Smoked labneh, pistachio, charred citrus</small></figcaption></figure>
          <div class="restaurant-tonight"><article><span>02</span><h4>Gulf redfish</h4><p>Brown butter, caper, market greens</p><b>$34</b></article><article><span>03</span><h4>44 Farms bavette</h4><p>Black garlic, embered onion, jus</p><b>$39</b></article></div>
        </section>
        <section class="restaurant-gather"><div><p>Private tables</p><h3>Bring the people.<br>We’ll tend the fire.</h3><span>Our hearth room hosts seated dinners for up to 28, with family-style menus shaped around the season.</span><button type="button" data-restaurant-route="story">Explore private dining</button></div></section>
      </section>

      <section class="restaurant-page restaurant-menu" data-restaurant-page="menu" hidden>
        <header class="restaurant-page-intro"><div><p>From the kitchen</p><h2>A changing menu,<br>grounded in fire.</h2></div><p>Our menu follows what is growing nearby and what belongs over flame. Ask your server about tonight’s market plates.</p></header>
        <div class="restaurant-menu-layout"><aside><p>Dinner menu</p><div class="restaurant-filters" role="group" aria-label="Menu category"><button type="button" class="active" data-menu-filter="all" aria-pressed="true">All</button><button type="button" data-menu-filter="snacks" aria-pressed="false">To begin</button><button type="button" data-menu-filter="fire" aria-pressed="false">From the fire</button><button type="button" data-menu-filter="garden" aria-pressed="false">Field &amp; garden</button><button type="button" data-menu-filter="sweet" aria-pressed="false">Sweet</button><button type="button" data-menu-filter="drinks" aria-pressed="false">Drinks</button></div><small>V — Vegetarian<br>GF — Gluten friendly<br>NA — No alcohol</small></aside>
          <div class="restaurant-menu-list"><ul>${menu.map(([category, name, description, price, note]) => `<li data-menu-item="${category}"><div><strong>${name}</strong><span>${description}</span></div><small>${note}</small><b>${price}</b></li>`).join('')}</ul><p>Menu and prices are part of this fictional concept and may change with the imaginary harvest.</p></div>
        </div>
        <section class="restaurant-menu-callout"><img src="${asset('assets/concepts/ember-vine-dish-v2.jpg')}" alt="A seasonal dish prepared over fire" width="1448" height="1086" loading="lazy"><div><p>Leave room for one more</p><h3>Let us cook for the table.</h3><span>A four-course, family-style menu is available nightly for the whole table.</span><b>$68 per guest</b><button type="button" data-restaurant-route="reserve">Book dinner</button></div></section>
      </section>

      <section class="restaurant-page restaurant-booking" data-restaurant-page="reserve" hidden>
        <header class="restaurant-page-intro"><div><p>Reservations</p><h2>Your table<br>is waiting.</h2></div><p>Choose a date, party size, and time. This interactive example stops before collecting any personal information.</p></header>
        <div class="restaurant-reservation-shell">
          <div class="restaurant-reservation-controls">
            <fieldset><legend>1 / Choose a night</legend><div class="restaurant-date-options">${[0,1,2,3].map((offset, index) => `<button type="button" data-restaurant-date-offset="${offset}" aria-pressed="${index === 0}"><small>${index === 0 ? 'Tonight' : 'Upcoming'}</small><strong>Loading</strong></button>`).join('')}</div></fieldset>
            <fieldset><legend>2 / Party size</legend><div class="restaurant-party-stepper"><button type="button" data-restaurant-party="minus" aria-label="Remove one guest">−</button><output id="restaurant-party-count" aria-live="polite">2 guests</output><button type="button" data-restaurant-party="plus" aria-label="Add one guest">+</button></div><small>For groups of 7 or more, please inquire about our hearth room.</small></fieldset>
            <fieldset><legend>3 / Available times</legend><div class="restaurant-time-options">${['5:00 PM','5:30 PM','6:15 PM','7:45 PM','8:30 PM','9:15 PM'].map((time,index) => `<button type="button" data-restaurant-time="${time}" aria-pressed="${index === 2}">${time}</button>`).join('')}</div></fieldset>
          </div>
          <aside class="restaurant-reservation-summary"><p>Your evening</p><h3 id="restaurant-reservation-date">Tonight</h3><dl><div><dt>Guests</dt><dd id="restaurant-reservation-guests">2 guests</dd></div><div><dt>Time</dt><dd id="restaurant-reservation-time">6:15 PM</dd></div><div><dt>Location</dt><dd>Ember &amp; Vine<br>Bishop Arts, Dallas</dd></div></dl><button type="button" id="restaurant-hold-table">Hold this table</button><small>No payment is taken when you reserve.</small><div class="restaurant-confirmation" id="restaurant-confirmation" role="status" aria-live="polite" hidden><strong>Table held—for the demo.</strong><span>This is a concept experience, so no reservation was sent and no personal information was collected.</span></div></aside>
        </div>
        <section class="restaurant-booking-note"><span>◆</span><p>Running late? Celebrating something? A real reservation flow can collect notes after a table is selected—without slowing down the first decision.</p></section>
      </section>

      <section class="restaurant-page restaurant-story" data-restaurant-page="story" hidden>
        <section class="restaurant-story-hero"><figure><img src="${asset('assets/concepts/ember-vine-interior-v2.jpg')}" alt="Ember and Vine’s candlelit hearth room" width="1586" height="992"><figcaption>THE HEARTH ROOM / BISHOP ARTS</figcaption></figure><div><p>Our table</p><h2>A neighborhood room, lit by fire.</h2><span>Ember &amp; Vine began with a simple idea: good cooking should carry the warmth of the people and place behind it.</span></div></section>
        <section class="restaurant-story-body"><blockquote>“Come for dinner. Leave with a new favorite table.”</blockquote><div><p>The menu is rooted in North Texas seasons, small farms, and the kind of food that gets better when it is passed around. Our open hearth does the heavy lifting; smoke, flame, and patience do the rest.</p><p>The room is polished but never precious. Come in from the neighborhood, order one more plate, and stay until the candles burn low.</p><dl><div><dt>Hours</dt><dd>Tue–Thu 5–10<br>Fri–Sun 5–11</dd></div><div><dt>Find us</dt><dd>408 W. Eighth Street<br>Dallas, Texas</dd></div><div><dt>Hospitality</dt><dd>Walk-ins welcome<br>Reservations encouraged</dd></div></dl></div></section>
        <section class="restaurant-private"><p>Gather at the hearth</p><h3>Private dinners,<br>without the private-room feeling.</h3><span>Host 12–28 guests around a shared table with a seasonal menu, dedicated service, and a view of the open fire.</span><button type="button" data-demo-message="Private dining inquiry opened — demonstration only.">Inquire about your date</button></section>
      </section>
    </main>
    <footer class="restaurant-footer"><button type="button" class="restaurant-wordmark" data-restaurant-route="home">Ember <i>&amp;</i> Vine</button><div><button type="button" data-restaurant-route="menu">Menu</button><button type="button" data-restaurant-route="story">Our table</button><button type="button" data-restaurant-route="reserve">Reservations</button></div><span>Bishop Arts / Dallas, Texas</span></footer>
  </article>`;
}

function renderEvents(asset) {
  return `<article class="concept-demo events-demo" data-concept-demo="events" hidden>
    <header class="events-nav">
      <button type="button" class="events-wordmark" data-event-route="home" aria-label="NightShift Audio home"><span>NS</span>/AUDIO</button>
      <nav aria-label="NightShift Audio navigation"><button type="button" data-event-route="home" aria-current="page">Home</button><button type="button" data-event-route="mixes">Mixes</button><button type="button" data-event-route="events">Events</button><button type="button" data-event-route="book">Book</button></nav>
      <button type="button" class="events-date" data-event-route="book">Check a date</button>
    </header>
    <main>
      <section class="event-page event-home" data-event-page="home">
        <section class="events-hero">
          <img src="${asset('assets/concepts/nightshift-audio.jpg')}" alt="A cobalt-lit DJ booth at a live event" width="1600" height="1000">
          <div class="events-overlay"><p>DJ / MC / Event production</p><h2>Make the room<br>move as one.</h2><div class="event-actions"><button type="button" class="event-primary" data-event-preview aria-pressed="false"><span>▶</span> Preview the energy</button><button type="button" data-event-route="book">Build your night</button></div></div>
          <div class="event-deck" aria-hidden="true"><span class="event-platter"><i></i></span><div class="event-wave">${Array.from({ length: 22 }, (_, index) => `<i style="--wave:${(index % 8) + 2}"></i>`).join('')}</div><small>LIVE REEL / 00:<b id="event-reel-time">00</b></small></div>
          <span class="events-stamp">NO DEAD AIR<br>NO GENERIC SETS</span>
        </section>
        <section class="events-proof"><p>Built for</p><div><span>Weddings</span><span>Brand events</span><span>Nightlife</span><span>Private parties</span></div></section>
        <section class="event-manifesto"><div><p>The NightShift method</p><h3>Read the room.<br>Then raise it.</h3></div><div><p>A packed floor is not an accident. Every set begins with the people, the timeline, and the moments that cannot miss.</p><dl><div><dt>01</dt><dd>Plan the arc</dd></div><div><dt>02</dt><dd>Protect the moments</dd></div><div><dt>03</dt><dd>Move with the room</dd></div></dl><button type="button" data-event-route="events">See the experience</button></div></section>
        <section class="events-close"><div><p>Saturday, 11:48 PM</p><h3>The timeline is handled.<br>The floor is full.</h3></div><button type="button" data-event-route="book">Check your date</button></section>
      </section>

      <section class="event-page event-mixes" data-event-page="mixes" hidden>
        <header class="event-page-intro"><div><p>Open-format, room-first programming</p><h2>Find your<br>frequency.</h2></div><p>Four sample directions—not rigid playlists. Choose a lane and NightShift builds the transitions around your crowd.</p></header>
        <div class="event-mix-grid">
          <button type="button" data-event-mix="Golden hour" data-event-mix-meta="Disco / R&amp;B / warm house" aria-pressed="false"><small>MIX 01 / 42:18</small><strong>Golden hour</strong><span>Disco, R&amp;B, warm house</span><i>Preview mix</i></button>
          <button type="button" data-event-mix="After dark" data-event-mix-meta="Hip-hop / club / edits" aria-pressed="false"><small>MIX 02 / 38:04</small><strong>After dark</strong><span>Hip-hop, club, edits</span><i>Preview mix</i></button>
          <button type="button" data-event-mix="Main character" data-event-mix-meta="Pop / throwbacks / singalongs" aria-pressed="false"><small>MIX 03 / 46:32</small><strong>Main character</strong><span>Pop, throwbacks, singalongs</span><i>Preview mix</i></button>
          <button type="button" data-event-mix="Night drive" data-event-mix-meta="Afro / house / global rhythm" aria-pressed="false"><small>MIX 04 / 40:11</small><strong>Night drive</strong><span>Afro, house, global rhythm</span><i>Preview mix</i></button>
        </div>
        <aside class="event-player" id="event-player" aria-live="polite"><button type="button" data-event-preview aria-pressed="false" aria-label="Play selected NightShift mix">▶</button><div><small>Selected preview</small><strong id="event-player-title">Choose a mix</strong><span id="event-player-meta">Your selection will load here.</span></div><div class="event-progress"><i id="event-progress"></i></div><time id="event-player-time">00:00</time></aside>
        <section class="event-mix-note"><p>Need a clean edit? A cultural favorite? A hard no?</p><h3>Your music brief matters.</h3><span>Planning includes must-plays, do-not-plays, pronunciations, and the songs attached to the moments people will remember.</span><button type="button" data-event-route="book">Start your brief</button></section>
      </section>

      <section class="event-page event-experience" data-event-page="events" hidden>
        <header class="event-page-intro"><div><p>More than a playlist</p><h2>Every cue.<br>Covered.</h2></div><p>From doors open to final track, NightShift manages the room’s energy and the production underneath it.</p></header>
        <section class="event-timeline" aria-label="Event production timeline"><article><span>04:00 PM</span><div><small>Load-in</small><h3>Quiet setup. Clean room.</h3><p>Audio, lighting, backups, and cable paths are tested before guests arrive.</p></div></article><article><span>06:30 PM</span><div><small>Guest arrival</small><h3>The room finds its pulse.</h3><p>Volume and selections build around conversation instead of fighting it.</p></div></article><article><span>08:05 PM</span><div><small>Key moments</small><h3>Names right. Cues exact.</h3><p>Introductions, speeches, formal dances, and transitions stay on the same clock.</p></div></article><article><span>09:12 PM</span><div><small>Open floor</small><h3>No dead air.</h3><p>The plan becomes responsive: requests, generations, and energy all shape the next record.</p></div></article></section>
        <section class="event-production"><div><p>Production desk</p><h3>One team.<br>One signal path.</h3><span>Choose a service to see how it supports the night.</span></div><div class="event-production-controls" role="group" aria-label="Production services"><button type="button" data-event-service="Room-tuned sound keeps speeches clear and the dance floor full without punishing the tables."><strong>Sound</strong><span>Wireless microphones / room coverage / backup playback</span></button><button type="button" data-event-service="Lighting builds a visual arc from dinner warmth to a kinetic late-night room."><strong>Lighting</strong><span>Uplighting / dance-floor movement / scene changes</span></button><button type="button" data-event-service="Clear MC work keeps attention where it belongs and the timeline moving naturally."><strong>MC</strong><span>Introductions / announcements / timeline direction</span></button><p id="event-service-detail">Select a production service.</p></div></section>
        <section class="event-testimonial"><blockquote>“We never looked at the clock once. Every transition just happened.”</blockquote><span>Fictional client note / Full room package</span></section>
      </section>

      <section class="event-page event-book" data-event-page="book" hidden>
        <header class="event-page-intro"><div><p>Build the night</p><h2>Start with<br>the room.</h2></div><p>This interactive planner demonstrates a clear booking flow. No reservation or personal information is sent.</p></header>
        <section class="events-packages" id="events-packages"><header><p>Choose the coverage</p><h3>A clear starting point.<br>A set built for your room.</h3></header><div class="event-package-grid">
          <button type="button" data-event-package="Essential" data-event-price="1450" aria-pressed="false"><small>01</small><strong>Essential</strong><span>DJ set<br>Sound system<br>Planning call</span><b>Select package</b></button>
          <button type="button" class="featured" data-event-package="Full room" data-event-price="2350" aria-pressed="false"><small>02 / Most requested</small><strong>Full room</strong><span>DJ + MC<br>Sound and lighting<br>Timeline planning</span><b>Select package</b></button>
          <button type="button" data-event-package="Production" data-event-price="3600" aria-pressed="false"><small>03</small><strong>Production</strong><span>Full event audio<br>Lighting design<br>On-site support</span><b>Select package</b></button>
        </div></section>
        <section class="event-planner"><div><fieldset><legend>How long is the event?</legend><div class="event-duration-options"><button type="button" data-event-duration="4 hours" data-event-duration-price="0" aria-pressed="true">4 hours</button><button type="button" data-event-duration="6 hours" data-event-duration-price="350" aria-pressed="false">6 hours</button><button type="button" data-event-duration="8 hours" data-event-duration-price="650" aria-pressed="false">8 hours</button></div></fieldset><fieldset><legend>Add to the room</legend><div class="event-addon-options"><button type="button" data-event-addon="Ceremony audio" data-event-addon-price="350" aria-pressed="false">Ceremony audio <span>+$350</span></button><button type="button" data-event-addon="Room uplighting" data-event-addon-price="500" aria-pressed="false">Room uplighting <span>+$500</span></button><button type="button" data-event-addon="Cold spark exit" data-event-addon-price="750" aria-pressed="false">Cold spark exit <span>+$750</span></button></div></fieldset></div><aside class="event-plan-summary"><p>Your NightShift plan</p><h3 id="event-plan-package">Choose coverage</h3><dl><div><dt>Duration</dt><dd id="event-plan-duration">4 hours</dd></div><div><dt>Add-ons</dt><dd id="event-plan-addons">None selected</dd></div><div><dt>Starting at</dt><dd id="event-plan-total">Select a package</dd></div></dl><button type="button" id="event-hold-date" disabled>Hold a demo date</button><small>Demonstration only. No payment or event request is sent.</small><div class="event-confirmation" id="event-confirmation" hidden><strong>Date ready for your review.</strong><span>Your selections stayed inside this demo.</span></div></aside></section>
      </section>
    </main>
    <footer class="events-footer"><button type="button" class="events-wordmark" data-event-route="home"><span>NS</span>/AUDIO</button><nav><button type="button" data-event-route="mixes">Mixes</button><button type="button" data-event-route="events">Events</button><button type="button" data-event-route="book">Book</button></nav><span>Concept booking experience / 2026</span></footer>
  </article>`;
}

function renderRetail(asset) {
  const products = [
    ['outerwear', 'Transit shell', 'Cobalt', 148, 'Weather-ready ripstop / relaxed layer'],
    ['outerwear', 'Blockline chore coat', 'Signal red', 168, 'Cotton twill / boxy fit'],
    ['tops', 'Studio weight tee', 'Stock', 48, '280gsm jersey / easy fit'],
    ['tops', 'Gridlock knit', 'Ink / workwear yellow', 92, 'Cotton knit / cropped box'],
    ['bottoms', 'Workshop cargo', 'Charcoal', 128, 'Washed twill / articulated knee'],
    ['accessories', 'Switchboard sling', 'Cobalt', 74, 'Ripstop / modular storage'],
    ['accessories', 'Five-panel signal cap', 'Signal red', 36, 'Washed cotton / adjustable'],
    ['accessories', 'Crew sock set', 'Stock', 24, 'Rib cotton / three pack']
  ];
  return `<article class="concept-demo retail-demo" data-concept-demo="retail" hidden>
    <header class="retail-nav"><button type="button" class="retail-wordmark" data-retail-route="home" aria-label="Common Thread Supply home"><span>COMMON</span><span>THREAD</span></button><nav aria-label="Common Thread navigation"><button type="button" data-retail-route="home" aria-current="page">Home</button><button type="button" data-retail-route="shop">Shop</button><button type="button" data-retail-route="lookbook">Lookbook</button><button type="button" data-retail-route="notes">Field notes</button></nav><button type="button" class="retail-bag" id="retail-bag">Bag <span id="retail-bag-count">0</span></button></header>
    <main>
      <section class="retail-page retail-home" data-retail-page="home">
        <section class="retail-hero"><div><p>DROP 05 / BUILT TO MOVE</p><h2>Daily uniform.<br>Harder working.</h2><div><button type="button" data-retail-route="shop">Shop the drop</button><button type="button" data-retail-route="lookbook">See it in motion</button></div></div><img src="${asset('assets/concepts/common-thread-supply.jpg')}" alt="An editorial arrangement of colorful streetwear and accessories" width="1600" height="1000"><b>COMMON GOODS<br>FOR UNCOMMON DAYS</b></section>
        <div class="retail-measure" aria-hidden="true"><span>0</span><i></i><span>25</span><i></i><span>50</span><i></i><span>75</span><i></i><span>100 CM</span></div>
        <section class="retail-drop"><header><p>New utility</p><h3>Eight pieces.<br>One working system.</h3><button type="button" data-retail-route="shop">View everything</button></header><div class="retail-drop-products">${products.slice(0, 4).map(([category, name, color, price], index) => `<button type="button" data-retail-open="${name}" data-retail-category="${category}" data-retail-color="${color}" data-retail-price="${price}" data-retail-spec="${products[index][4]}" data-retail-crop="${index + 1}"><span class="retail-product-photo retail-crop-${index + 1}" style="background-image:url('${asset('assets/concepts/common-thread-products-v2.png')}')"></span><strong>${name}</strong><small>${color}</small><b>$${price}</b></button>`).join('')}</div></section>
        <section class="retail-home-note"><div><span>FIELD NOTE 021</span><h3>Designed from the pocket out.</h3><p>Every seam, opening, and layer earns its place. Nothing is added just to make the product louder.</p><button type="button" data-retail-route="notes">Read the field notes</button></div><span class="retail-thread-mark" aria-hidden="true">CT<br>05</span></section>
      </section>

      <section class="retail-page retail-shop" data-retail-page="shop" hidden>
        <header class="retail-page-intro"><div><p>Drop 05 / complete system</p><h2>Made for<br>the whole day.</h2></div><p>Layerable shapes, useful storage, and fabric that improves after the first scuff.</p></header>
        <div class="retail-shop-controls"><p id="retail-product-count">8 products</p><div class="retail-filters" role="group" aria-label="Product category"><button type="button" class="active" data-retail-filter="all" aria-pressed="true">All</button><button type="button" data-retail-filter="outerwear" aria-pressed="false">Outerwear</button><button type="button" data-retail-filter="tops" aria-pressed="false">Tops</button><button type="button" data-retail-filter="bottoms" aria-pressed="false">Bottoms</button><button type="button" data-retail-filter="accessories" aria-pressed="false">Accessories</button></div></div>
        <div class="retail-products">${products.map(([category, name, color, price, spec], index) => `<article data-retail-item="${category}"><button type="button" class="retail-product-art" data-retail-open="${name}" data-retail-category="${category}" data-retail-color="${color}" data-retail-price="${price}" data-retail-spec="${spec}" data-retail-crop="${index + 1}" aria-label="View ${name}"><span class="retail-product-photo retail-crop-${index + 1}" style="background-image:url('${asset('assets/concepts/common-thread-products-v2.png')}')"></span><i>${String(index + 1).padStart(2, '0')}</i><b>View piece</b></button><div><strong>${name}</strong><span>${color}</span><b>$${price}</b></div></article>`).join('')}</div>
      </section>

      <section class="retail-page retail-product" data-retail-page="product" hidden><button type="button" class="retail-product-back" data-retail-route="shop">← Back to all pieces</button><div class="retail-product-layout"><figure><span id="retail-detail-photo" class="retail-product-photo retail-crop-1" style="background-image:url('${asset('assets/concepts/common-thread-products-v2.png')}')"></span><figcaption>DROP 05 / GARMENT SPEC</figcaption></figure><section><p id="retail-detail-category">Outerwear</p><h2 id="retail-detail-name">Transit shell</h2><strong id="retail-detail-price">$148</strong><span id="retail-detail-spec">Weather-ready ripstop / relaxed layer</span><div class="retail-color-picker"><p>Color / <b id="retail-detail-color">Cobalt</b></p><div><button type="button" data-retail-color-option="Cobalt" class="cobalt active" aria-label="Cobalt" aria-pressed="true"></button><button type="button" data-retail-color-option="Signal red" class="signal" aria-label="Signal red" aria-pressed="false"></button><button type="button" data-retail-color-option="Stock" class="stock" aria-label="Stock" aria-pressed="false"></button></div></div><fieldset><legend>Choose a size</legend><div class="retail-size-options"><button type="button" data-retail-size="XS" aria-pressed="false">XS</button><button type="button" data-retail-size="S" aria-pressed="false">S</button><button type="button" data-retail-size="M" aria-pressed="true">M</button><button type="button" data-retail-size="L" aria-pressed="false">L</button><button type="button" data-retail-size="XL" aria-pressed="false">XL</button></div></fieldset><button type="button" class="retail-add" id="retail-add-product">Add to bag — <span>$148</span></button><small>Demonstration shop. No payment or order is processed.</small><details><summary>Construction</summary><p>Reinforced stress points, repairable hardware, and low-profile internal labeling.</p></details><details><summary>Fit and care</summary><p>Relaxed unisex fit. Cold wash, hang dry, and keep it in rotation.</p></details></section></div></section>

      <section class="retail-page retail-lookbook" data-retail-page="lookbook" hidden>
        <header class="retail-page-intro"><div><p>Field study / three uniforms</p><h2>Wear the<br>whole system.</h2></div><p>One compact collection, styled across the commute, the workday, and whatever starts after it.</p></header>
        <section class="retail-look retail-look-one"><div class="retail-look-image"><img src="${asset('assets/concepts/common-thread-supply.jpg')}" alt="Colorful Common Thread pieces arranged as a daily uniform" width="1200" height="900"><span>LOOK 01</span></div><div><small>07:42 / IN TRANSIT</small><h3>Weather changes.<br>The plan doesn’t.</h3><p>Transit shell over the studio tee with Workshop cargo and the Switchboard sling.</p><button type="button" data-retail-look="outerwear">Shop the transit layer</button></div></section>
        <section class="retail-look retail-look-two"><div><small>14:18 / ON THE CLOCK</small><h3>Built to work.<br>Cut to leave.</h3><p>Blockline chore coat, Gridlock knit, and a cap that survives the bottom of the bag.</p><button type="button" data-retail-look="tops">Shop the studio layer</button></div><div class="retail-look-image"><span class="retail-product-photo retail-crop-2" style="background-image:url('${asset('assets/concepts/common-thread-products-v2.png')}')"></span><span>LOOK 02</span></div></section>
        <section class="retail-lookbook-close"><p>A uniform should remove one decision from your day.</p><button type="button" data-retail-route="shop">Build yours</button></section>
      </section>

      <section class="retail-page retail-notes" data-retail-page="notes" hidden>
        <header class="retail-page-intro"><div><p>Why we make it this way</p><h2>Use leaves<br>a better mark.</h2></div><p>Common Thread is a fictional label with a practical point of view: clothing becomes personal through repetition, repair, and time.</p></header>
        <section class="retail-story"><img src="${asset('assets/concepts/common-thread-supply.jpg')}" alt="Streetwear pieces arranged in a bold editorial flat lay" width="1200" height="800"><div><p>Field note 017</p><h3>Buy less.<br>Wear it harder.</h3><span>The best piece is not the newest one. It is the one that already knows the route.</span></div></section>
        <section class="retail-materials"><header><span>MATERIAL INDEX</span><h3>Fewer fabrics.<br>Better reasons.</h3></header><div><article><b>01</b><h4>Ripstop nylon</h4><p>Light, packable, and reinforced against small tears before they become large ones.</p></article><article><b>02</b><h4>Washed twill</h4><p>Dense enough for work, softened before cutting so the fit feels familiar on day one.</p></article><article><b>03</b><h4>Heavy jersey</h4><p>A stable 280gsm knit that holds shape without feeling armored.</p></article></div></section>
        <section class="retail-repair"><div><span>KEEP IT MOVING</span><h3>Repair is part<br>of the design.</h3></div><p>Loose button, tired zipper, torn pocket? A real shop could turn this section into repair intake, care instructions, and parts ordering—all before replacement becomes the answer.</p><button type="button" data-demo-message="Repair intake opened — demonstration only.">Start a repair</button></section>
      </section>
    </main>
    <div class="retail-cart-scrim" id="retail-cart-scrim" hidden></div><aside class="retail-cart" id="retail-cart" hidden aria-labelledby="retail-cart-title"><button type="button" id="retail-cart-close" aria-label="Close bag">×</button><p>Your bag / demo</p><h3 id="retail-cart-title">Ready to move.</h3><div id="retail-cart-items"><p>Your selected concept products will appear here.</p></div><dl><dt>Subtotal</dt><dd id="retail-cart-total">$0</dd></dl><button type="button" id="retail-checkout">Demo checkout</button><small>No order, payment, or personal information is collected.</small></aside>
    <footer class="retail-footer"><button type="button" class="retail-wordmark" data-retail-route="home"><span>COMMON</span><span>THREAD</span></button><nav><button type="button" data-retail-route="shop">Shop</button><button type="button" data-retail-route="lookbook">Lookbook</button><button type="button" data-retail-route="notes">Field notes</button></nav><span>Fictional concept storefront / 2026</span></footer>
  </article>`;
}

function renderGoodwork(asset) {
  const serviceRows = [
    ['Climate', 'Cooling & heating', 'No-cool calls, tune-ups, thermostat installs, and seasonal maintenance.', '$129'],
    ['Power', 'Electrical', 'Dead outlets, panel diagnostics, lighting, fans, and dedicated circuits.', '$119'],
    ['Water', 'Plumbing', 'Leaks, drains, fixtures, disposals, and water-heater diagnostics.', '$109'],
    ['Care', 'Whole-home upkeep', 'One coordinated visit for the small repairs that keep getting postponed.', '$149']
  ];
  return `<article class="concept-demo goodwork-demo" data-concept-demo="goodwork" hidden>
    <header class="goodwork-nav"><button type="button" class="goodwork-wordmark" data-goodwork-route="home" aria-label="Goodwork Home Company home"><span>GOOD</span><b>WORK</b></button><nav aria-label="Goodwork pages"><button type="button" data-goodwork-route="services">Services</button><button type="button" data-goodwork-route="estimate">Estimate</button><button type="button" data-goodwork-route="schedule">Schedule</button><button type="button" data-goodwork-route="track">Track a visit</button></nav><button type="button" class="goodwork-primary-nav" data-goodwork-route="estimate">Get help</button></header>
    <main>
      <section class="goodwork-page goodwork-home" data-goodwork-page="home">
        <section class="goodwork-service-check"><div><p>Service-area check</p><h3>Is Goodwork on your block?</h3></div><div><label for="goodwork-zip">Enter a DFW ZIP code</label><span><input id="goodwork-zip" name="goodwork-zip" inputmode="numeric" maxlength="5" autocomplete="postal-code" placeholder="75208"><button type="button" id="goodwork-check-zip">Check ZIP</button></span><p id="goodwork-zip-status" role="status">Demo tip: try a ZIP beginning with 750, 751, 752, 753, or 760.</p></div></section>
        <section class="goodwork-hero"><div class="goodwork-hero-copy"><p>Home service without the runaround</p><h2>Fix the problem.<br>Keep the day.</h2><span>Clear starting prices, two-hour arrival windows, and one place to see what happens next.</span><div><button type="button" class="goodwork-button primary" data-goodwork-route="estimate">Start an estimate</button><button type="button" class="goodwork-text-button" data-goodwork-route="track">Track today’s visit</button></div><dl><div><dt>Next opening</dt><dd>Today / 2–4 PM</dd></div><div><dt>Service area</dt><dd>32 DFW ZIP codes</dd></div></dl></div><figure><img src="${asset('assets/concepts/goodwork-home-v1.png')}" alt="A Goodwork technician arriving at a home with an unbranded service van" width="1536" height="1024"><figcaption><span>JOB GW–2048</span><b>TECHNICIAN EN ROUTE</b><i aria-hidden="true"></i></figcaption></figure></section>
        <section class="goodwork-diagnostic"><header><div><p>Start where the problem is</p><h3>Show us the room.<br>We’ll show you the next step.</h3></div><span>Select an area in the house.</span></header><div class="goodwork-diagnostic-grid"><div class="goodwork-house" aria-label="Interactive house systems"><div class="goodwork-roof"><span>GOODWORK HOME DIAGNOSTIC</span></div><button type="button" class="goodwork-zone zone-climate active" data-goodwork-zone="Cooling & heating" data-goodwork-zone-copy="Uneven temperature, warm air, strange sounds, or a system that will not start." data-goodwork-zone-price="$129 diagnostic" data-goodwork-zone-slot="Today / 2–4 PM" aria-pressed="true"><span>Attic + air</span><b>Climate</b></button><button type="button" class="goodwork-zone zone-power" data-goodwork-zone="Electrical" data-goodwork-zone-copy="Dead outlets, tripping breakers, flickering lights, or a panel that needs a closer look." data-goodwork-zone-price="$119 diagnostic" data-goodwork-zone-slot="Tomorrow / 8–10 AM" aria-pressed="false"><span>Panel + rooms</span><b>Power</b></button><button type="button" class="goodwork-zone zone-water" data-goodwork-zone="Plumbing" data-goodwork-zone-copy="Slow drains, small leaks, low pressure, fixture trouble, or water-heater issues." data-goodwork-zone-price="$109 diagnostic" data-goodwork-zone-slot="Today / 4–6 PM" aria-pressed="false"><span>Kitchen + bath</span><b>Water</b></button><button type="button" class="goodwork-zone zone-care" data-goodwork-zone="Whole-home upkeep" data-goodwork-zone-copy="A practical punch list for doors, fixtures, filters, mounting, caulk, and small repairs." data-goodwork-zone-price="$149 first hour" data-goodwork-zone-slot="Friday / 10 AM–12 PM" aria-pressed="false"><span>Everywhere else</span><b>Care</b></button></div><aside class="goodwork-diagnostic-ticket"><p>Selected system</p><h4 id="goodwork-zone-name">Cooling &amp; heating</h4><span id="goodwork-zone-copy">Uneven temperature, warm air, strange sounds, or a system that will not start.</span><dl><div><dt>Starting visit</dt><dd id="goodwork-zone-price">$129 diagnostic</dd></div><div><dt>Next window</dt><dd id="goodwork-zone-slot">Today / 2–4 PM</dd></div></dl><button type="button" data-goodwork-start="Cooling & heating">Estimate this repair</button><small>No charge is made in this demonstration.</small></aside></div></section>
        <section class="goodwork-job-board"><header><p>One visit. No mystery.</p><h3>Every job reads like a work order.</h3></header><ol><li><b>Describe it</b><span>Choose the system and the symptom.</span></li><li><b>See the range</b><span>Review a clear starting estimate.</span></li><li><b>Pick a window</b><span>Choose a two-hour arrival period.</span></li><li><b>Follow along</b><span>Track status from confirmed to complete.</span></li></ol></section>
      </section>

      <section class="goodwork-page goodwork-services" data-goodwork-page="services" hidden><header class="goodwork-page-head"><p>Practical help for the whole home</p><h2>One number.<br>Four systems.</h2><span>Choose the problem—not the trade vocabulary. Goodwork routes the right technician and the right tools.</span></header><div class="goodwork-service-ledger">${serviceRows.map(([code, name, copy, price], index) => `<article><span>${String(index + 1).padStart(2, '0')} / ${code}</span><h3>${name}</h3><p>${copy}</p><b>Visits from ${price}</b><button type="button" data-goodwork-service="${name}">Estimate this service</button></article>`).join('')}</div><section class="goodwork-service-proof"><img src="${asset('assets/concepts/goodwork-home-v1.png')}" alt="A residential service technician walking from a van toward a home" width="1536" height="1024"><div><p>Goodwork standard</p><h3>Prepared before the doorbell.</h3><ul><li>Photo and arrival updates</li><li>Written scope before work begins</li><li>One-year workmanship promise</li><li>Clean workspace at closeout</li></ul><button type="button" data-goodwork-route="schedule">See available windows</button></div></section></section>

      <section class="goodwork-page goodwork-estimate" data-goodwork-page="estimate" hidden><header class="goodwork-page-head compact"><p>Interactive estimate builder</p><h2>Tell us what changed.</h2><span>Choose what you know. A real technician would confirm the final scope on site.</span></header><div class="goodwork-estimator"><section><fieldset><legend><span>1</span> Which system?</legend><div class="goodwork-choice-grid systems"><button type="button" data-goodwork-system="Cooling & heating" data-goodwork-base="129" aria-pressed="false">Cooling &amp; heating<small>From $129</small></button><button type="button" data-goodwork-system="Electrical" data-goodwork-base="119" aria-pressed="false">Electrical<small>From $119</small></button><button type="button" data-goodwork-system="Plumbing" data-goodwork-base="109" aria-pressed="false">Plumbing<small>From $109</small></button><button type="button" data-goodwork-system="Whole-home upkeep" data-goodwork-base="149" aria-pressed="false">Whole-home upkeep<small>From $149</small></button></div></fieldset><fieldset><legend><span>2</span> What changed?</legend><div class="goodwork-choice-grid issues"><button type="button" data-goodwork-issue="Stopped working" data-goodwork-issue-price="90" aria-pressed="false">Stopped working</button><button type="button" data-goodwork-issue="Works sometimes" data-goodwork-issue-price="45" aria-pressed="false">Works sometimes</button><button type="button" data-goodwork-issue="Leak or damage" data-goodwork-issue-price="120" aria-pressed="false">Leak or damage</button><button type="button" data-goodwork-issue="Maintenance" data-goodwork-issue-price="0" aria-pressed="false">Maintenance</button></div></fieldset><fieldset><legend><span>3</span> What kind of visit?</legend><div class="goodwork-choice-grid visit"><button type="button" data-goodwork-urgency="Routine" data-goodwork-urgency-price="0" aria-pressed="true">Routine<small>Next available</small></button><button type="button" data-goodwork-urgency="Soon" data-goodwork-urgency-price="49" aria-pressed="false">Soon<small>Within 48 hours</small></button><button type="button" data-goodwork-urgency="Priority" data-goodwork-urgency-price="99" aria-pressed="false">Priority<small>First available</small></button></div></fieldset></section><aside class="goodwork-estimate-ticket"><p>Working estimate</p><h3 id="goodwork-estimate-total">Choose a system</h3><dl><div><dt>System</dt><dd id="goodwork-estimate-system">Not selected</dd></div><div><dt>Issue</dt><dd id="goodwork-estimate-issue">Not selected</dd></div><div><dt>Visit</dt><dd id="goodwork-estimate-urgency">Routine</dd></div></dl><div class="goodwork-estimate-range"><span>Estimated starting range</span><b id="goodwork-estimate-range">—</b></div><button type="button" id="goodwork-estimate-continue" disabled>Choose an arrival window</button><small>Demonstration estimate only. No request or payment is sent.</small></aside></div></section>

      <section class="goodwork-page goodwork-schedule" data-goodwork-page="schedule" hidden><header class="goodwork-page-head compact"><p>Arrival windows</p><h2>Pick a window.<br>Keep your day.</h2><span>Goodwork uses two-hour windows and sends an update when the technician starts driving.</span></header><div class="goodwork-scheduler"><section><fieldset><legend>Choose a day</legend><div class="goodwork-date-options"><button type="button" data-goodwork-day-offset="0" aria-pressed="true"><small>Today</small><b>Sep 15</b></button><button type="button" data-goodwork-day-offset="1" aria-pressed="false"><small>Tomorrow</small><b>Sep 16</b></button><button type="button" data-goodwork-day-offset="2" aria-pressed="false"><small>Thursday</small><b>Sep 17</b></button><button type="button" data-goodwork-day-offset="3" aria-pressed="false"><small>Friday</small><b>Sep 18</b></button></div></fieldset><fieldset><legend>Choose an arrival window</legend><div class="goodwork-window-options"><button type="button" data-goodwork-window="8–10 AM" aria-pressed="false">8–10 AM <small>2 openings</small></button><button type="button" data-goodwork-window="10 AM–12 PM" aria-pressed="false">10 AM–12 PM <small>1 opening</small></button><button type="button" data-goodwork-window="2–4 PM" aria-pressed="true">2–4 PM <small>Next available</small></button><button type="button" data-goodwork-window="4–6 PM" aria-pressed="false">4–6 PM <small>3 openings</small></button></div></fieldset></section><aside class="goodwork-schedule-ticket"><p>Visit summary</p><h3 id="goodwork-schedule-service">Home diagnostic</h3><dl><div><dt>Day</dt><dd id="goodwork-schedule-day">Today</dd></div><div><dt>Window</dt><dd id="goodwork-schedule-window">2–4 PM</dd></div><div><dt>Starting range</dt><dd id="goodwork-schedule-range">Confirmed after selection</dd></div></dl><button type="button" id="goodwork-hold-window">Hold demo window</button><small>This demonstration does not book a visit or collect personal information.</small><div class="goodwork-schedule-confirmation" id="goodwork-schedule-confirmation" hidden><b>Window prepared.</b><span>No appointment was sent. In a production site, contact details and final confirmation would come next.</span></div></aside></div></section>

      <section class="goodwork-page goodwork-track" data-goodwork-page="track" hidden><header class="goodwork-page-head compact"><p>Sample job / GW–2048</p><h2>Your visit,<br>without the guessing.</h2><span>This demonstration advances through the same updates a customer would see on service day.</span></header><div class="goodwork-tracker"><section class="goodwork-route-map"><div class="goodwork-route-line"><i id="goodwork-route-progress"></i><span class="start">SHOP</span><span class="mid">ON THE WAY</span><span class="end">YOUR HOME</span><b id="goodwork-route-van" aria-hidden="true">▰</b></div><div class="goodwork-tech"><span>RM</span><div><small>Your technician</small><b>Riley M.</b><p>Electrical specialist / Goodwork team 04</p></div></div></section><aside><p>Live job status</p><h3 id="goodwork-track-status">Visit confirmed</h3><span id="goodwork-track-copy">Your window is reserved for today from 2–4 PM.</span><ol><li class="complete">Confirmed</li><li>Preparing</li><li>En route</li><li>Arrived</li><li>Complete</li></ol><button type="button" id="goodwork-track-advance">Advance demo status</button><small>Demo tracking uses fictional technician and location information.</small></aside></div></section>
    </main>
    <footer class="goodwork-footer"><button type="button" class="goodwork-wordmark" data-goodwork-route="home"><span>GOOD</span><b>WORK</b></button><p>Home systems / clearly handled</p><nav><button type="button" data-goodwork-route="services">Services</button><button type="button" data-goodwork-route="estimate">Estimate</button><button type="button" data-goodwork-route="track">Track</button></nav><span>Fictional concept / no services are booked</span></footer>
  </article>`;
}

function renderMorrow(asset) {
  const providers = [
    ['AP', 'Dr. Amara Patel', 'Restorative care', 'Thoughtful repairs and long-term planning.'],
    ['JL', 'Dr. Jordan Lee', 'Preventive care', 'Comfort-first visits and clear next steps.'],
    ['MR', 'Dr. Mateo Ruiz', 'Cosmetic care', 'Conservative changes designed around you.']
  ];
  return `<article class="concept-demo morrow-demo" data-concept-demo="morrow" hidden>
    <header class="morrow-nav"><button type="button" class="morrow-mark" data-morrow-route="home" aria-label="Morrow Dental Studio home"><span>M</span>Morrow</button><nav aria-label="Morrow Dental Studio pages"><button type="button" data-morrow-route="care">Care</button><button type="button" data-morrow-route="team">Team</button><button type="button" data-morrow-route="visit">New patients</button><button type="button" data-morrow-route="portal">Patient portal</button></nav><button type="button" class="morrow-appointment" data-morrow-route="visit">Request a visit</button></header>
    <main>
      <section class="morrow-page morrow-home" data-morrow-page="home">
        <section class="morrow-hero"><div><p>Modern dentistry / clearly explained</p><h2>Care that makes room for questions.</h2><span>Understand the plan, choose the pace, and know what comes next before treatment begins.</span><div><button type="button" class="morrow-primary" data-morrow-route="visit">Plan a first visit</button><button type="button" data-morrow-route="care">Explore care</button></div><dl><div><dt>New patients</dt><dd>Welcome</dd></div><div><dt>Next opening</dt><dd>Thursday / 10:30</dd></div><div><dt>Languages</dt><dd>English / Spanish</dd></div></dl></div><figure><img src="${asset('assets/concepts/morrow-dental-v1.png')}" alt="A calm fictional dental studio with a clinician reviewing a care plan" width="1536" height="1024"><figcaption><span>YOUR VISIT / YOUR PACE</span><b>Care notes ready</b></figcaption></figure></section>
        <section class="morrow-path"><header><p>Start with what you need</p><h3>Not sure what to call it?<br>That is completely fine.</h3><span>Choose the outcome you want. Morrow translates it into a simple care path.</span></header><div class="morrow-path-grid"><div class="morrow-needs" role="group" aria-label="Choose a dental care need"><button type="button" data-morrow-need="Relief" data-morrow-need-copy="A focused exam, comfort plan, and the soonest appropriate appointment." aria-pressed="true"><i>01</i><b>Relief</b><span>Something hurts or changed</span></button><button type="button" data-morrow-need="Restore" data-morrow-need-copy="A complete look at damaged or missing teeth with repair options in plain language." aria-pressed="false"><i>02</i><b>Restore</b><span>Repair function and comfort</span></button><button type="button" data-morrow-need="Protect" data-morrow-need-copy="Preventive care, home routines, and a schedule built around your risk factors." aria-pressed="false"><i>03</i><b>Protect</b><span>Stay ahead of problems</span></button><button type="button" data-morrow-need="Confidence" data-morrow-need-copy="Conservative cosmetic options, previews, and a plan that still looks like you." aria-pressed="false"><i>04</i><b>Confidence</b><span>Explore a thoughtful change</span></button></div><aside><p>Your care path</p><h4 id="morrow-path-title">Relief</h4><span id="morrow-path-copy">A focused exam, comfort plan, and the soonest appropriate appointment.</span><ol><li class="active">Tell us what changed</li><li>Meet the right clinician</li><li>Review choices together</li></ol><button type="button" data-morrow-route="visit">See visit options</button><small>No symptoms or medical details are collected in this demonstration.</small></aside></div></section>
        <section class="morrow-principles"><article><b>Listen first</b><p>The exam begins with what you notice and what matters to you.</p></article><article><b>Show the why</b><p>Photos, timelines, and costs live beside every recommendation.</p></article><article><b>Choose together</b><p>A care plan can be phased without losing the bigger picture.</p></article></section>
      </section>

      <section class="morrow-page morrow-care" data-morrow-page="care" hidden><header class="morrow-page-head"><p>Care, translated</p><h2>Understand the goal<br>before the procedure.</h2><span>Browse by what you want to solve. Each path explains the visit, likely next step, and questions worth asking.</span></header><div class="morrow-care-index"><article><span>Comfort</span><h3>Urgent and restorative care</h3><p>Focused exams, fillings, crowns, root-canal coordination, and repair planning.</p><button type="button" data-morrow-care="Relief">Build a relief path</button></article><article><span>Prevention</span><h3>Everyday oral health</h3><p>Exams, cleanings, gum-health support, sealants, and custom home-care plans.</p><button type="button" data-morrow-care="Protect">Build a prevention path</button></article><article><span>Function</span><h3>Replace and rebuild</h3><p>Bridges, implant restoration, bite evaluation, and phased full-mouth planning.</p><button type="button" data-morrow-care="Restore">Build a restoration path</button></article><article><span>Confidence</span><h3>Subtle cosmetic care</h3><p>Whitening, bonding, aligner screening, and conservative smile design.</p><button type="button" data-morrow-care="Confidence">Build a confidence path</button></article></div><aside class="morrow-cost-note"><div><p>Clear before care</p><h3>One plan. Three useful numbers.</h3></div><dl><div><dt>Practice fee</dt><dd>What the visit costs</dd></div><div><dt>Estimated benefit</dt><dd>What a plan may cover</dd></div><div><dt>Your estimate</dt><dd>What remains before treatment</dd></div></dl></aside></section>

      <section class="morrow-page morrow-team" data-morrow-page="team" hidden><header class="morrow-page-head"><p>People, not provider codes</p><h2>Meet the person<br>behind the plan.</h2><span>Choose a fictional clinician to see how a provider-matching experience can guide a new patient.</span></header><div class="morrow-team-grid">${providers.map(([initials,name,specialty,copy], index) => `<button type="button" data-morrow-provider="${name}" data-morrow-specialty="${specialty}" data-morrow-provider-copy="${copy}" aria-pressed="${index === 0}"><span>${initials}</span><small>${specialty}</small><b>${name}</b><p>${copy}</p><i>View match</i></button>`).join('')}</div><aside class="morrow-provider-match"><div><p>Your provider match</p><h3 id="morrow-provider-name">Dr. Amara Patel</h3><span id="morrow-provider-specialty">Restorative care</span></div><p id="morrow-provider-copy">Thoughtful repairs and long-term planning.</p><button type="button" data-morrow-route="visit">See this provider’s openings</button></aside></section>

      <section class="morrow-page morrow-visit" data-morrow-page="visit" hidden><header class="morrow-page-head compact"><p>New-patient planner</p><h2>A first visit,<br>without the paperwork fog.</h2><span>Check a fictional benefit plan, choose a visit type, and prepare an appointment window. No personal or medical information is requested.</span></header><div class="morrow-visit-shell"><section><fieldset><legend>Check a sample benefit plan</legend><label for="morrow-insurance">Select a fictional plan</label><div class="morrow-insurance-row"><select id="morrow-insurance"><option value="">Choose a plan</option><option value="Aster PPO">Aster PPO</option><option value="Northline Dental">Northline Dental</option><option value="Brightway Plus">Brightway Plus</option><option value="Self-pay">No insurance / self-pay</option></select><button type="button" id="morrow-check-insurance">Check support</button></div><p id="morrow-insurance-status" role="status">This checker uses fictional plans and never contacts an insurer.</p></fieldset><fieldset><legend>What brings you in?</legend><div class="morrow-visit-types"><button type="button" data-morrow-visit="Complete first visit" data-morrow-duration="75 minutes" aria-pressed="true">Complete first visit<small>Exam, images, and cleaning when appropriate</small></button><button type="button" data-morrow-visit="Focused concern" data-morrow-duration="45 minutes" aria-pressed="false">Focused concern<small>One specific change or discomfort</small></button><button type="button" data-morrow-visit="Consultation" data-morrow-duration="40 minutes" aria-pressed="false">Consultation<small>Talk through options before treatment</small></button></div></fieldset><fieldset><legend>Choose a sample opening</legend><div class="morrow-time-slots"><button type="button" data-morrow-time="Thu / 10:30 AM" aria-pressed="true">Thu<small>10:30 AM</small></button><button type="button" data-morrow-time="Thu / 2:00 PM" aria-pressed="false">Thu<small>2:00 PM</small></button><button type="button" data-morrow-time="Fri / 9:15 AM" aria-pressed="false">Fri<small>9:15 AM</small></button><button type="button" data-morrow-time="Mon / 3:30 PM" aria-pressed="false">Mon<small>3:30 PM</small></button></div></fieldset></section><aside class="morrow-visit-summary"><p>Visit preview</p><h3 id="morrow-visit-name">Complete first visit</h3><dl><div><dt>With</dt><dd id="morrow-visit-provider">Dr. Amara Patel</dd></div><div><dt>Length</dt><dd id="morrow-visit-duration">75 minutes</dd></div><div><dt>Opening</dt><dd id="morrow-visit-time">Thu / 10:30 AM</dd></div></dl><button type="button" id="morrow-hold-visit">Prepare demo visit</button><small>This does not schedule care or collect personal information.</small><div id="morrow-visit-confirmation" role="status" hidden><b>Visit prepared.</b><span>A production experience would collect contact details only after this step.</span></div></aside></div></section>

      <section class="morrow-page morrow-portal" data-morrow-page="portal" hidden><header class="morrow-portal-head"><div><p>Sample patient / MD–1042</p><h2>Your care,<br>in one clear view.</h2></div><button type="button" data-demo-message="Secure portal sign-in reached — demonstration only.">Secure sign in</button></header><div class="morrow-portal-grid"><aside><span>Next visit</span><h3>Thursday<br>10:30 AM</h3><p>Complete first visit<br>with Dr. Amara Patel</p><button type="button" data-demo-message="Visit details opened — demonstration only.">View visit details</button></aside><section><header><p>Current care plan</p><span id="morrow-care-progress-label">Step 1 of 4</span></header><ol class="morrow-care-progress"><li class="complete">Comprehensive exam</li><li>Review findings</li><li>Choose a treatment path</li><li>Confirm next visit</li></ol><button type="button" id="morrow-advance-care">Advance sample care plan</button></section><section class="morrow-documents"><header><p>Documents</p><span>2 ready</span></header><button type="button" data-demo-message="Care estimate preview opened — fictional document only."><b>Care estimate</b><span>Updated today</span><i>View</i></button><button type="button" data-demo-message="Visit summary preview opened — fictional document only."><b>Visit summary</b><span>May 14</span><i>View</i></button></section></div><p class="morrow-portal-note">Fictional portal demonstration. No real medical, insurance, appointment, or identity information appears here.</p></section>
    </main>
    <footer class="morrow-footer"><button type="button" class="morrow-mark" data-morrow-route="home"><span>M</span>Morrow</button><p>Care explained before care begins.</p><nav><button type="button" data-morrow-route="care">Care</button><button type="button" data-morrow-route="team">Team</button><button type="button" data-morrow-route="visit">New patients</button></nav><small>Fictional dental concept / no care is scheduled</small></footer>
  </article>`;
}

function renderRelay(asset) {
  const loads = [
    ['RN–482901', 'Dallas → Tulsa', 'In transit', 'Today / 18:40', 'on-time'],
    ['RN–482744', 'Fort Worth → Austin', 'At destination', 'Delivered / 11:16', 'delivered'],
    ['RN–482630', 'Plano → Oklahoma City', 'Weather hold', 'Tomorrow / 09:20', 'delayed'],
    ['RN–482519', 'Dallas → Houston', 'Pickup ready', 'Today / 16:00', 'on-time']
  ];
  return `<article class="concept-demo relay-demo" data-concept-demo="relay" hidden>
    <header class="relay-nav"><button type="button" class="relay-mark" data-relay-route="home" aria-label="Relay North Logistics home"><span>RN</span><b>Relay North</b></button><nav aria-label="Relay North pages"><button type="button" data-relay-route="capabilities">Capabilities</button><button type="button" data-relay-route="quote">Quote</button><button type="button" data-relay-route="track">Track</button><button type="button" data-relay-route="portal">Operations</button></nav><button type="button" class="relay-login" data-relay-route="portal">Client login</button></header>
    <main>
      <section class="relay-page relay-home" data-relay-page="home"><section class="relay-hero"><img src="${asset('assets/concepts/relay-north-v1.png')}" alt="A fictional regional freight hub operating at blue hour" width="1536" height="1024"><div class="relay-hero-copy"><p>Regional freight / live visibility</p><h2>Every mile<br>accounted for.</h2><span>Quote, dispatch, track, document, and resolve from one operating picture.</span><div><button type="button" class="relay-primary" data-relay-route="quote">Build a freight quote</button><button type="button" data-relay-route="track">Track RN–482901</button></div></div><aside><small>CONTROL TOWER / 21:42</small><dl><div><dt>Active loads</dt><dd>148</dd></div><div><dt>On schedule</dt><dd>94.6%</dd></div><div><dt>Exceptions</dt><dd>03</dd></div></dl><span><i></i> Network operating normally</span></aside></section><section class="relay-route-strip" aria-label="Sample shipment route"><span>DFW ORIGIN</span><i></i><b>RELAY 482901 / IN TRANSIT</b><i></i><span>TULSA DESTINATION</span></section><section class="relay-home-grid"><div><p>The network</p><h3>Built for the<br>messy middle.</h3></div><article><b>01</b><h4>Quote with context</h4><p>Lane, equipment, timing, and accessorials stay attached to the rate.</p></article><article><b>02</b><h4>See every handoff</h4><p>Dispatch, checkpoints, documents, and exceptions share one timeline.</p></article><article><b>03</b><h4>Close with proof</h4><p>Delivery status, proof of delivery, and invoices finish the same record.</p></article></section></section>

      <section class="relay-page relay-capabilities" data-relay-page="capabilities" hidden><header class="relay-page-head"><p>Freight built around the lane</p><h2>Capacity where<br>the work happens.</h2><span>Regional full truckload, time-sensitive freight, and coordinated final-mile coverage across a fictional south-central network.</span></header><div class="relay-cap-grid"><article><span>FTL</span><h3>Full truckload</h3><p>Dry van capacity, dedicated lanes, and drop-trailer programs.</p><dl><div><dt>Equipment</dt><dd>53′ dry van</dd></div><div><dt>Coverage</dt><dd>TX / OK / AR / LA</dd></div></dl><button type="button" data-relay-quote-type="Full truckload">Price this move</button></article><article><span>EXP</span><h3>Expedited</h3><p>Protected capacity for freight that cannot wait for tomorrow.</p><dl><div><dt>Response</dt><dd>Under 30 min</dd></div><div><dt>Visibility</dt><dd>Live checkpoints</dd></div></dl><button type="button" data-relay-quote-type="Expedited">Price this move</button></article><article><span>FNL</span><h3>Final mile</h3><p>Scheduled delivery, site coordination, and signed closeout.</p><dl><div><dt>Stops</dt><dd>1–12</dd></div><div><dt>Proof</dt><dd>Photo + signature</dd></div></dl><button type="button" data-relay-quote-type="Final mile">Price this move</button></article></div><section class="relay-lane-table"><header><h3>Sample lane performance</h3><span>Past 30 fictional days</span></header><div><b>Dallas → Tulsa</b><span>4 departures / day</span><span>98.1% on time</span></div><div><b>DFW → Austin</b><span>6 departures / day</span><span>96.8% on time</span></div><div><b>Dallas → Houston</b><span>8 departures / day</span><span>97.4% on time</span></div><div><b>Fort Worth → OKC</b><span>3 departures / day</span><span>95.9% on time</span></div></section></section>

      <section class="relay-page relay-quote" data-relay-page="quote" hidden><header class="relay-page-head compact"><p>Interactive lane estimate</p><h2>Build the move.<br>See the range.</h2><span>A production tool can connect pricing rules and capacity. This demonstration calculates a fictional planning range only.</span></header><div class="relay-quote-shell"><section><fieldset><legend>Origin and destination</legend><div class="relay-select-row"><label for="relay-origin">Origin<select id="relay-origin"><option value="Dallas">Dallas, TX</option><option value="Fort Worth">Fort Worth, TX</option><option value="Austin">Austin, TX</option><option value="Houston">Houston, TX</option></select></label><span>→</span><label for="relay-destination">Destination<select id="relay-destination"><option value="Tulsa">Tulsa, OK</option><option value="Austin">Austin, TX</option><option value="Houston">Houston, TX</option><option value="Oklahoma City">Oklahoma City, OK</option></select></label></div></fieldset><fieldset><legend>Freight type</legend><div class="relay-quote-types"><button type="button" data-relay-freight="Full truckload" data-relay-rate="1280" aria-pressed="true">Full truckload<small>53′ dry van</small></button><button type="button" data-relay-freight="Expedited" data-relay-rate="1840" aria-pressed="false">Expedited<small>Protected capacity</small></button><button type="button" data-relay-freight="Final mile" data-relay-rate="760" aria-pressed="false">Final mile<small>Scheduled delivery</small></button></div></fieldset><fieldset><legend>Timing</legend><div class="relay-timing"><button type="button" data-relay-timing="Flexible" data-relay-timing-rate="0" aria-pressed="true">Flexible<small>Best available rate</small></button><button type="button" data-relay-timing="Specific day" data-relay-timing-rate="180" aria-pressed="false">Specific day<small>Protected window</small></button><button type="button" data-relay-timing="Next available" data-relay-timing-rate="420" aria-pressed="false">Next available<small>Priority dispatch</small></button></div></fieldset></section><aside class="relay-quote-ticket"><p>Planning range / not a rate offer</p><h3 id="relay-quote-lane">Dallas → Tulsa</h3><dl><div><dt>Service</dt><dd id="relay-quote-service">Full truckload</dd></div><div><dt>Timing</dt><dd id="relay-quote-timing">Flexible</dd></div><div><dt>Transit</dt><dd id="relay-quote-transit">1 business day</dd></div></dl><div><span>Estimated range</span><b id="relay-quote-total">$1,280–$1,510</b></div><button type="button" id="relay-save-quote">Prepare demo quote</button><small>No freight request, company data, or payment is sent.</small><p id="relay-quote-confirmation" role="status"></p></aside></div></section>

      <section class="relay-page relay-track" data-relay-page="track" hidden><header class="relay-page-head compact"><p>Shipment visibility</p><h2>One reference.<br>The whole route.</h2><span>Try sample tracking number <b>RN–482901</b>. The demonstration uses fictional locations, times, and documents.</span></header><div class="relay-track-shell"><section class="relay-track-search"><label for="relay-track-input">Tracking number</label><span><input id="relay-track-input" autocomplete="off" value="RN-482901"><button type="button" id="relay-track-submit">Track shipment</button></span><p id="relay-track-message" role="status">Sample shipment ready to track.</p></section><section class="relay-map"><div class="relay-map-grid" aria-hidden="true"></div><div class="relay-map-route"><i id="relay-map-progress"></i><span class="origin">DFW<br><b>Picked up</b></span><span class="checkpoint">ARDMORE<br><b>Checkpoint</b></span><span class="destination">TULSA<br><b>Destination</b></span><em id="relay-map-truck">▰</em></div><aside><small>RN–482901</small><h3 id="relay-track-status">In transit</h3><p id="relay-track-copy">Departed the Ardmore checkpoint. Estimated arrival today at 6:40 PM.</p><button type="button" id="relay-track-advance">Advance sample status</button></aside></section><ol class="relay-events"><li class="complete"><time>09:18</time><b>Picked up</b><span>Dallas, TX</span></li><li class="complete"><time>12:46</time><b>Checkpoint cleared</b><span>Ardmore, OK</span></li><li><time>18:40</time><b>Expected delivery</b><span>Tulsa, OK</span></li></ol></div></section>

      <section class="relay-page relay-portal" data-relay-page="portal" hidden><header class="relay-portal-head"><div><p>Operations portal / Northstar account</p><h2>148 active loads.<br>One operating picture.</h2></div><dl><div><dt>On time</dt><dd>94.6%</dd></div><div><dt>Exceptions</dt><dd>03</dd></div><div><dt>Delivered today</dt><dd>27</dd></div></dl></header><div class="relay-portal-tools"><div role="group" aria-label="Filter sample shipments"><button type="button" data-relay-filter="all" aria-pressed="true">All loads</button><button type="button" data-relay-filter="on-time" aria-pressed="false">On schedule</button><button type="button" data-relay-filter="delayed" aria-pressed="false">Exceptions</button><button type="button" data-relay-filter="delivered" aria-pressed="false">Delivered</button></div><span>Last sync / just now</span></div><div class="relay-portal-grid"><section class="relay-loads"><header><span>Load</span><span>Lane</span><span>Status</span><span>ETA</span></header>${loads.map(([id,lane,status,eta,state], index) => `<button type="button" data-relay-load="${id}" data-relay-load-state="${state}" data-relay-load-lane="${lane}" data-relay-load-status="${status}" data-relay-load-eta="${eta}" class="${index === 0 ? 'active' : ''}"><b>${id}</b><span>${lane}</span><i>${status}</i><small>${eta}</small></button>`).join('')}</section><aside class="relay-load-detail"><p>Selected load</p><h3 id="relay-detail-id">RN–482901</h3><span id="relay-detail-lane">Dallas → Tulsa</span><dl><div><dt>Status</dt><dd id="relay-detail-status">In transit</dd></div><div><dt>ETA</dt><dd id="relay-detail-eta">Today / 18:40</dd></div><div><dt>Equipment</dt><dd>53′ dry van</dd></div></dl><div><button type="button" data-demo-message="Proof of delivery preview opened — fictional document only.">Proof of delivery</button><button type="button" data-demo-message="Invoice preview opened — fictional document only.">Invoice</button><button type="button" data-demo-message="Bill of lading preview opened — fictional document only.">Bill of lading</button></div><small>All loads and documents in this portal are fictional.</small></aside></div></section>
    </main>
    <footer class="relay-footer"><button type="button" class="relay-mark" data-relay-route="home"><span>RN</span><b>Relay North</b></button><p>Quote / dispatch / visibility / closeout</p><nav><button type="button" data-relay-route="quote">Quote</button><button type="button" data-relay-route="track">Track</button><button type="button" data-relay-route="portal">Operations</button></nav><small>Fictional logistics concept / no freight is moved</small></footer>
  </article>`;
}
